### ISSUE TITLE
waring of install epistat

### ISSUE THREAD

**Issue by wiesswang** [gFedonin/EpiStat#2]
Hi @gFedonin,

During the installation of the software, it was found that the following data was missing

WARNING: the following files are missing in your kit:
	examples/intergene/mtb_gwas/Amikacin/Amikacin.epistat.prm
	examples/intergene/mtb_gwas/Amikacin/Amikacin.lower.pvalue.fdr.prm
	examples/intergene/mtb_gwas/Amikacin/Amikacin.upper.pvalue.fdr.prm
	examples/intergene/mtb_gwas/Amikacin/Amikacin.xparr
	examples/intragene/alleles/mtb/phen/9drugs.all.mk_coevolmtx.prm
	examples/intragene/alleles/mtb/phen/9drugs.lower.pvalue.unord_pairs.sites2.fdr.prm
	examples/intragene/alleles/mtb/phen/9drugs.mk_coevolmtx.prm
	examples/intragene/alleles/mtb/phen/9drugs.pairs2.upper.FDR5.mk_summary.cfg
	examples/intragene/alleles/mtb/phen/9drugs.sites2.lower.FDR5.mk_summary.cfg
	examples/intragene/alleles/mtb/phen/9drugs.upper.pvalue.unord_pairs.pairs2.fdr.prm
	examples/intragene/alleles/mtb/phen/9drugs.xparr
	examples/intragene/alleles/mtb/phen/epistat.phen.prm
	examples/intragene/alleles/mtb/phen/estimate_fdr.txt
	examples/intragene/alleles/mtb/phen/min_RR_SR.site2pheno
	examples/intragene/alleles/mtb/phen/run_epistat.prm
Please inform the author.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Epistat' version 'v0.10.1'

Can you provide the above data again！
Thank you for your help!

**Comment by AlexeyDNeverov** [comment]
Thank you! We added missed files into the repository.
